# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
                ('vendor', models.CharField(choices=[('IBM', 'IBM Computers'), ('MST', 'Microsoft'), ('APL', 'Apple'), ('ADB', 'Adobe'), ('AMZ', 'Amazon'), ('TAT', 'Tata')], max_length=3)),
            ],
        ),
    ]
