# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_sys',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
