# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmaster',
            name='cfo_email',
            field=models.CharField(default=b'rahul.makhare9@gmail.com', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='branchmaster',
            name='cfo_name',
            field=models.CharField(default=b'Rahul Makhare', editable=False, max_length=50),
        ),
    ]
