# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='location',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
