# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_user_info_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
