# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 03:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0003_user_info_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
