# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nature_of_expenses', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True,max_length=45, null=True)),
                ('name_of_party', models.CharField(blank=True,max_length=45, null=True)),
                ('name_of_bank', models.CharField(blank=True,max_length=45, null=True)),
                ('bank_account_no', models.IntegerField(blank=True, max_length=45, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        ]