# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('payment_request_form', '0003_paymentmaster_branch_name'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='paymentmaster',
        #     name='amount',
        #     field=models.FloatField(default=0.0),
        # ),
        # migrations.AddField(
        #     model_name='paymentmaster',
        #     name='bank_acc_no',
        #     field=models.IntegerField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='paymentmaster',
        #     name='dept_name',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.DesignationMaster'),
        # ),
        # migrations.AddField(
        #     model_name='paymentmaster',
        #     name='ifsc_code',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
    ]
