# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('payment_request_form', '0004_auto_20180605_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),

    ]
