# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('payment_request_form', '0005_auto_20180605_1115'),
    ]

    operations = [

    ]
