# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0007_auto_20180605_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='head_of_accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_request_form.HeadOfAccounts'),
        ),
    ]
