# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0009_auto_20180605_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_code', models.IntegerField(blank=True, null=True)),
                ('gl_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='headofaccounts',
            name='gl_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_request_form.GLMaster'),
        ),
    ]
