# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0011_auto_20180606_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
