# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0012_paymentmaster_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofaccounts',
            name='gl_data',
        ),
        migrations.AddField(
            model_name='headofaccounts',
            name='gl_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headofaccounts',
            name='gl_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='GLMaster',
        ),
    ]
