# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0014_auto_20180606_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='approve_lvl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='approve_lvl2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='approve_lvl3',
            field=models.BooleanField(default=False),
        ),
    ]
