# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0015_auto_20180607_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
