# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0017_paymentmaster_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='approval_date_lvl1',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='approval_date_lvl2',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='approval_date_lvl3',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='name_of_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='name_of_party',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
