# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0018_auto_20180607_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='bm_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='dm_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='rm_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
