# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0020_auto_20180608_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='document',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
