# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request_form', '0021_paymentmaster_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_doc', models.FileField(null=True, upload_to='csv_doc/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentmaster',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='approval_date_lvl4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='approve_lvl4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='cfo_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
