

#  EMPLOYEE TABLE CONSTANT


ACTIVE = "Active"
INACTIVE = "INACTIVE"
REJECTED = "Rejected"



# EMPAPP DETAIL CONSTANT

ACKL = 'Acknowledged' 
INPROGRESS = 'In Process'
APPROVED = 'APPROVED'
APP_REJECTED = 'REJECTED'


# APPROVAL PROCESS CONSTANT
SYSTEM = 'SYSTEM'

APR_1_SN = "APPROVAL_1_SEND"
APR_2_SN = "APPROVAL_2_SEND"
APR_3_SN = "APPROVAL_3_SEND"

APR_1_APD = "APPROVAL_1_APPROVED"
APR_2_APD = "APPROVAL_2_APPROVED"
APR_3_APD = "APPROVAL_3_APPROVED"


APR_1_RJD = "APPROVAL_1_REJECTED"
APR_2_RJD = "APPROVAL_2_REJECTED"
APR_3_RJD = "APPROVAL_3_REJECTED"


ACC_REQ_SEND = 'ACC_REQ_SEND'
ACC_CREATED = 'ACC_CREATED'

ACC_CREDENT_SEND = 'ACC_CREDENT_SEND'


HOST='192.168.1.202'
SYSMAIL = 'omiharjani@gmail.com'
MAIL=''





